const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const package = require('./package.json');

const chalk = require('chalk');
const prompt = require('prompt-sync')({
  sigint: false
});
const program = require('commander');
const yaml = require('js-yaml');

const WORDPRESS_URL = 'https://github.com/Seravo/wordpress.git'; // We do not want to deal with authenticatio
const TMP_DIR = path.join(__dirname, 'clone');

program
  .version(package.version)
  .usage('[options]')
  .option(
    '-n, --name <name>',
    'Project name, no spaces or special chars other than dot (.).'
  )
  .option(
    '-r, --repository <repository>',
    'Repository path for project. Just the path, example: redandblue/skeleton'
  )
  .parse(process.argv);

if (fs.existsSync('./config.yml')) {
  console.log(chalk.yellow('Found config.yml in project, assuming existing project'));
  process.exit(0);
} else {
  console.log(chalk.green('Kickstarting new project'));
  if (package.name === 'skeleton') {
    console.log(chalk.red('You should rename this package in package.json.'));
    process.exit(1);
  }
  createNewProject();
}


function generateConfig() {
  if (!fs.existsSync('./config.yml')) {
    const doc = yaml.safeLoad(fs.readFileSync('./config-sample.yml'), 'utf8');
    const options = {
      project_name: typeof program.name === 'string' || package.name !== 'skeleton'
      ? package.name !== 'skeleton' ? package.name : program.name
      : prompt('Project name [a-z, 0-9, -], will be used as dev domain: '), // relic, too tired to clean
      // username: (() => {
        // console.log(chalk.yellow('Your username is redandblue.admin'));
        // console.log(chalk.yellow('You will receive your password a bit later. Save it to LastPass!'));
        // console.log(chalk.yellow('Enter password generated by LastPass: '));
        // return 'redandblue.admin';
      // })(),
      // password: typeof program.password === 'string'
      // ? program.password
      // : prompt('') // plaintext and empty
    };

    doc.name = options.project_name;
    doc.development.domains[0] = `${doc.name.toLowerCase()}.local`;

    doc.custom = (() => {
      const keys = Object.keys(options);
      return keys.filter(key => ['project_name', 'password'].indexOf(key))
        .reduce((acc, key) => {
          // This is ridiculous. ES6: { ...{ [key]: options[key] }, ...acc }
          const obj = {};
          obj[key] = options[key];

          return Object.assign(obj, acc);
        }, {});
    })();

    fs.writeFileSync('./config.yml', yaml.safeDump(doc));
    return true;
  } else {
    console.log(chalk.red('config.yml already exists, refusing to create it!'));
    return false;
  }
}

function createNewProject() {
  // cp.execSync(path.join(__dirname, 'update-core.sh'));
  generateConfig();
  setupRepository();

  console.log(chalk.green('All done! Proceed to running Vagrant'));

  // cloneWordPressBase()
  // .then(result => {
  // setupRepository();
  // });
}

function setupRepository() {
  const url = 'git@github.com:'.concat(typeof program.repository === 'string'
    ? program.repository
    : console.log('Repository path, example: redandbluefi/skeleton') ||
      prompt('Make it if you don\'t have it yet: ')).concat('.git');
  const upstream = package.repository.url
    .replace('git+ssh://', '')
    .replace('github.com/', 'github.com:')
    .concat('.git');

  cp.execSync(`git remote add upstream ${upstream}`);
  cp.execSync(`git remote remove origin`);
  cp.execSync(`git remote add origin ${url}`);
}

